# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e8a1b22c4714737192dfb84ec800afc"
name = "exe-payout-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_all_orders,read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
